/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.fineract.accounting.provisioning.domain;

import org.apache.fineract.infrastructure.core.domain.AbstractPersistableCustom;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "m_provisioning_batch_journal")
public class ProvisionBatchJournal extends AbstractPersistableCustom {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "batch_id", nullable = false)
    private ProvisionBatch batch;

    /**
     * Unique reference generated by Fineract for this
     * aggregated journal.
     */
    @Column(name = "journal_reference", nullable = false, length = 150, unique = true)
    private String journalReference;

    /**
     * transactionId sent to Odoo.
     */
    @Column(name = "transaction_id", nullable = false, length = 150)
    private String transactionId;

    /**
     * ref sent to Odoo.
     */
    @Column(name = "reference", nullable = false, length = 255)
    private String reference;

    /**
     * Accounting date sent to Odoo.
     */
    @Column(name = "entry_date", nullable = false)
    private LocalDate entryDate;

    /**
     * Currency of this aggregated journal.
     */
    @Column(name = "currency_code", nullable = false, length = 10)
    private String currencyCode;

    @Column(name = "status", nullable = false, length = 30)
    private String status;

    /**
     * ID returned by Odoo after the journal is successfully posted.
     */
    @Column(name = "odoo_journal_id", length = 100)
    private String odooJournalId;

    @Column(
            name = "total_debit",
            nullable = false,
            precision = 19,
            scale = 6
    )
    private BigDecimal totalDebit = BigDecimal.ZERO;

    @Column(
            name = "total_credit",
            nullable = false,
            precision = 19,
            scale = 6
    )
    private BigDecimal totalCredit = BigDecimal.ZERO;

    /**
     * Number of source provisioning entries contributing
     * to this aggregated journal.
     */
    @Column(name = "entry_count", nullable = false)
    private Integer entryCount = 0;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "posted_at")
    private LocalDateTime postedAt;

    @Column(name = "failure_reason", columnDefinition = "TEXT")
    private String failureReason;

    @OneToMany(
            mappedBy = "journal",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<ProvisionBatchJournalLine> journalLines = new ArrayList<>();

    protected ProvisionBatchJournal() {}

    public ProvisionBatchJournal(
            final String journalReference,
            final String transactionId,
            final String reference,
            final LocalDate entryDate,
            final String currencyCode
    ) {
        this.journalReference = journalReference;
        this.transactionId = transactionId;
        this.reference = reference;
        this.entryDate = entryDate;
        this.currencyCode = currencyCode;
        this.status = ProvisionBatchStatus.CREATED.name();
        this.createdAt = LocalDateTime.now(ZoneId.systemDefault());
    }

    public void setBatch(final ProvisionBatch batch) {
        this.batch = batch;
    }

    public void addJournalLine(final ProvisionBatchJournalLine line) {
        this.journalLines.add(line);
        line.setJournal(this);
    }

    public ProvisionBatch getBatch() {
        return batch;
    }

    public String getJournalReference() {
        return journalReference;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public String getReference() {
        return reference;
    }

    public LocalDate getEntryDate() {
        return entryDate;
    }

    public String getCurrencyCode() {
        return currencyCode;
    }

    public String getStatus() {
        return status;
    }

    public String getOdooJournalId() {
        return odooJournalId;
    }

    public BigDecimal getTotalDebit() {
        return totalDebit;
    }

    public BigDecimal getTotalCredit() {
        return totalCredit;
    }

    public Integer getEntryCount() {
        return entryCount;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getPostedAt() {
        return postedAt;
    }

    public String getFailureReason() {
        return failureReason;
    }

    public List<ProvisionBatchJournalLine> getJournalLines() {
        return journalLines;
    }

    public void setStatus(final ProvisionBatchStatus status) {
        this.status = status.name();
    }

    public void setOdooJournalId(final String odooJournalId) {
        this.odooJournalId = odooJournalId;
    }

    public void setPostedAt(final LocalDateTime postedAt) {
        this.postedAt = postedAt;
    }

    public void setFailureReason(final String failureReason) {
        this.failureReason = failureReason;
    }

    public void setTotalDebit(final BigDecimal totalDebit) {
        this.totalDebit = totalDebit;
    }

    public void setTotalCredit(final BigDecimal totalCredit) {
        this.totalCredit = totalCredit;
    }

    public void incrementEntryCount() {
        this.entryCount++;
    }
}